//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculadoraCliente.ClienteSecretoRemoto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteInformacoesSecretas", Namespace="http://schemas.datacontract.org/2004/07/WCFProjeto")]
    [System.SerializableAttribute()]
    public partial class ClienteInformacoesSecretas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteSecretoRemoto.IClienteSecreto")]
    public interface IClienteSecreto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSecreto/cadastrar", ReplyAction="http://tempuri.org/IClienteSecreto/cadastrarResponse")]
        string cadastrar(CalculadoraCliente.ClienteSecretoRemoto.ClienteInformacoesSecretas cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteSecreto/cadastrar", ReplyAction="http://tempuri.org/IClienteSecreto/cadastrarResponse")]
        System.Threading.Tasks.Task<string> cadastrarAsync(CalculadoraCliente.ClienteSecretoRemoto.ClienteInformacoesSecretas cliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteSecretoChannel : CalculadoraCliente.ClienteSecretoRemoto.IClienteSecreto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteSecretoClient : System.ServiceModel.ClientBase<CalculadoraCliente.ClienteSecretoRemoto.IClienteSecreto>, CalculadoraCliente.ClienteSecretoRemoto.IClienteSecreto {
        
        public ClienteSecretoClient() {
        }
        
        public ClienteSecretoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteSecretoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteSecretoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteSecretoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string cadastrar(CalculadoraCliente.ClienteSecretoRemoto.ClienteInformacoesSecretas cliente) {
            return base.Channel.cadastrar(cliente);
        }
        
        public System.Threading.Tasks.Task<string> cadastrarAsync(CalculadoraCliente.ClienteSecretoRemoto.ClienteInformacoesSecretas cliente) {
            return base.Channel.cadastrarAsync(cliente);
        }
    }
}
